workflows:
  build-android:
    name: Build APK for ancha_dub_player
    max_build_duration: 15
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK in release mode
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - nastyancha@gmail.com
          
